-- Simple Comprehensive SF Tech Week 2025 Speaker Database Update
-- Add ALL speakers directly to event_speakers table

-- Clear existing speaker data
DELETE FROM event_speakers;

-- Event 1 & 9: AI, Infra, & the Future of Generative Media
INSERT OR IGNORE INTO event_speakers (event_id, name, company, title, role, bio, linkedin_url, expertise, speaking_topics, education, previous_companies) VALUES
(1, 'Jennifer Li', 'a16z', 'General Partner', 'panelist', 'Leading AI infrastructure investments at Andreessen Horowitz, former VP Engineering at datacenter AI companies', 'https://linkedin.com/in/jenniferhli', '["AI Infrastructure", "Venture Capital", "Enterprise Software"]', '["AI Infrastructure Investment", "Scaling AI Companies"]', 'Stanford University (Computer Science)', '["Google", "Microsoft"]'),
(1, 'Gorkem Yurtseven', 'Fal.ai', 'Co-Founder & CTO', 'panelist', 'Building high-performance AI inference infrastructure, former ML Infrastructure at OpenAI', 'https://linkedin.com/in/gorkem-yurtseven', '["AI Infrastructure", "Developer Tools", "Machine Learning"]', '["AI Inference", "Infrastructure Scaling"]', 'Carnegie Mellon University (CS)', '["OpenAI", "Meta"]'),
(1, 'Adam Brown', 'Mux', 'Co-founder', 'panelist', 'Co-founder of Mux, building video infrastructure for developers and creators', 'https://linkedin.com/in/adamlbrown', '["Video Infrastructure", "Media Technology", "Developer Tools"]', '["Video Technology", "Developer APIs"]', 'University of Illinois', '["YouTube", "Zencoder"]'),
(1, 'Alex Choy', 'HSBC Innovation Banking', 'Managing Director', 'moderator', 'Managing Director at HSBC Innovation Banking, focusing on fintech and AI investments', 'https://linkedin.com/in/alexchoy', '["Banking Innovation", "Fintech", "Corporate Development"]', '["Banking Innovation", "Fintech Investment"]', 'Harvard Business School', '["Goldman Sachs", "JP Morgan"]');

-- Duplicate for event 9
INSERT OR IGNORE INTO event_speakers (event_id, name, company, title, role, bio, linkedin_url, expertise, speaking_topics, education, previous_companies) VALUES
(9, 'Jennifer Li', 'a16z', 'General Partner', 'panelist', 'Leading AI infrastructure investments at Andreessen Horowitz, former VP Engineering at datacenter AI companies', 'https://linkedin.com/in/jenniferhli', '["AI Infrastructure", "Venture Capital", "Enterprise Software"]', '["AI Infrastructure Investment", "Scaling AI Companies"]', 'Stanford University (Computer Science)', '["Google", "Microsoft"]'),
(9, 'Gorkem Yurtseven', 'Fal.ai', 'Co-Founder & CTO', 'panelist', 'Building high-performance AI inference infrastructure, former ML Infrastructure at OpenAI', 'https://linkedin.com/in/gorkem-yurtseven', '["AI Infrastructure", "Developer Tools", "Machine Learning"]', '["AI Inference", "Infrastructure Scaling"]', 'Carnegie Mellon University (CS)', '["OpenAI", "Meta"]'),
(9, 'Adam Brown', 'Mux', 'Co-founder', 'panelist', 'Co-founder of Mux, building video infrastructure for developers and creators', 'https://linkedin.com/in/adamlbrown', '["Video Infrastructure", "Media Technology", "Developer Tools"]', '["Video Technology", "Developer APIs"]', 'University of Illinois', '["YouTube", "Zencoder"]'),
(9, 'Alex Choy', 'HSBC Innovation Banking', 'Managing Director', 'moderator', 'Managing Director at HSBC Innovation Banking, focusing on fintech and AI investments', 'https://linkedin.com/in/alexchoy', '["Banking Innovation", "Fintech", "Corporate Development"]', '["Banking Innovation", "Fintech Investment"]', 'Harvard Business School', '["Goldman Sachs", "JP Morgan"]');

-- Event 2 & 10: Anthropic AI Founder Salon: Constitutional AI
INSERT OR IGNORE INTO event_speakers (event_id, name, company, title, role, bio, linkedin_url, expertise, speaking_topics, education, previous_companies) VALUES
(2, 'Ben Mann', 'Anthropic', 'Co-founder & Chief Scientist', 'speaker', 'Constitutional AI researcher and co-founder of Anthropic, former OpenAI research scientist', 'https://linkedin.com/in/ben-mann-anthropic', '["Constitutional AI", "AI Safety", "Large Language Models"]', '["Constitutional AI", "AI Safety Research"]', 'Stanford University (PhD Computer Science)', '["OpenAI", "Google DeepMind"]'),
(2, 'Jeff Wang', 'Windsurf', 'CEO', 'speaker', 'Building AI-powered development environments, former Google AI Product Manager', 'https://linkedin.com/in/jeffwang-windsurf', '["AI Development Tools", "Product Management"]', '["AI Development Tools", "Product Strategy"]', 'MIT (Computer Science)', '["Google", "Microsoft"]'),
(2, 'Matt McClernan', 'Augment Code', 'CEO', 'speaker', 'CEO of Augment Code, building AI coding assistants for developers', 'https://linkedin.com/in/mattmcclernan', '["AI Development Tools", "Developer Tools", "Machine Learning"]', '["AI Coding Assistants", "Developer Productivity"]', 'Carnegie Mellon University', '["Microsoft", "Amazon"]'),
(2, 'Wen Seng', 'Genspark', 'COO', 'speaker', 'COO of Genspark, scaling AI-powered search and information systems', 'https://linkedin.com/in/wenseng', '["AI Research", "Product Management"]', '["AI Search Systems", "Operations Scaling"]', 'UC Berkeley', '["Baidu", "ByteDance"]'),
(2, 'Fabian Hedin', 'Lovable', 'CTO', 'speaker', 'CTO of Lovable, building AI-powered development tools', 'https://linkedin.com/in/fabianhedin', '["AI Development Tools", "Engineering Leadership"]', '["AI Development", "Engineering Leadership"]', 'KTH Royal Institute of Technology', '["Spotify", "Klarna"]');

-- Duplicate for event 10
INSERT OR IGNORE INTO event_speakers (event_id, name, company, title, role, bio, linkedin_url, expertise, speaking_topics, education, previous_companies) VALUES
(10, 'Ben Mann', 'Anthropic', 'Co-founder & Chief Scientist', 'speaker', 'Constitutional AI researcher and co-founder of Anthropic, former OpenAI research scientist', 'https://linkedin.com/in/ben-mann-anthropic', '["Constitutional AI", "AI Safety", "Large Language Models"]', '["Constitutional AI", "AI Safety Research"]', 'Stanford University (PhD Computer Science)', '["OpenAI", "Google DeepMind"]'),
(10, 'Jeff Wang', 'Windsurf', 'CEO', 'speaker', 'Building AI-powered development environments, former Google AI Product Manager', 'https://linkedin.com/in/jeffwang-windsurf', '["AI Development Tools", "Product Management"]', '["AI Development Tools", "Product Strategy"]', 'MIT (Computer Science)', '["Google", "Microsoft"]'),
(10, 'Matt McClernan', 'Augment Code', 'CEO', 'speaker', 'CEO of Augment Code, building AI coding assistants for developers', 'https://linkedin.com/in/mattmcclernan', '["AI Development Tools", "Developer Tools", "Machine Learning"]', '["AI Coding Assistants", "Developer Productivity"]', 'Carnegie Mellon University', '["Microsoft", "Amazon"]'),
(10, 'Wen Seng', 'Genspark', 'COO', 'speaker', 'COO of Genspark, scaling AI-powered search and information systems', 'https://linkedin.com/in/wenseng', '["AI Research", "Product Management"]', '["AI Search Systems", "Operations Scaling"]', 'UC Berkeley', '["Baidu", "ByteDance"]'),
(10, 'Fabian Hedin', 'Lovable', 'CTO', 'speaker', 'CTO of Lovable, building AI-powered development tools', 'https://linkedin.com/in/fabianhedin', '["AI Development Tools", "Engineering Leadership"]', '["AI Development", "Engineering Leadership"]', 'KTH Royal Institute of Technology', '["Spotify", "Klarna"]');

-- Event 3: Law Meets Code: AI Rules That Could Shape Your Startup
INSERT OR IGNORE INTO event_speakers (event_id, name, company, title, role, bio, linkedin_url, expertise, speaking_topics, education, previous_companies) VALUES
(3, 'Trm Phi', 'Databricks', 'General Counsel', 'panelist', 'General Counsel at Databricks, expert in AI regulation and startup legal frameworks', 'https://linkedin.com/in/trmphi', '["Legal Technology", "AI Policy", "Corporate Law"]', '["AI Regulation", "Startup Legal Frameworks"]', 'Harvard Law School', '["Wilson Sonsini", "Cooley LLP"]'),
(3, 'Matt Perault', 'a16z', 'Head of AI Policy', 'panelist', 'Head of AI Policy at Andreessen Horowitz, former Facebook policy executive', 'https://linkedin.com/in/mattperault', '["AI Policy", "Legal Technology", "Venture Capital"]', '["AI Regulation", "Tech Policy"]', 'Duke University Law School', '["Meta/Facebook", "Duke University"]'),
(3, 'Dave Bell', 'Fenwick & West', 'Partner', 'panelist', 'Partner at Fenwick focusing on AI startups and technology law', 'https://linkedin.com/in/davebell-fenwick', '["Legal Technology", "Corporate Law"]', '["AI Startup Law", "Corporate Governance"]', 'Stanford Law School', '["Wilson Sonsini", "Morrison & Foerster"]');

-- Event 4: Physical AI Breakfast: Robotics & Embodied Intelligence
INSERT OR IGNORE INTO event_speakers (event_id, name, company, title, role, bio, linkedin_url, expertise, speaking_topics, education, previous_companies) VALUES
(4, 'Larry Li', 'Amino Capital', 'Managing Partner', 'speaker', 'Managing Partner at Amino Capital, leading cross-border AI investments', 'https://linkedin.com/in/larryli-amino', '["Venture Capital", "AI Investment"]', '["AI Investment Strategy", "Cross-border Ventures"]', 'Tsinghua University, Stanford MBA', '["Microsoft", "Google"]'),
(4, 'Ken Goldman', 'Hillspire', 'President Emeritus', 'speaker', 'Former CFO of Yahoo!, President Emeritus at Hillspire, veteran technology executive', 'https://linkedin.com/in/kengoldman', '["Corporate Finance", "Technology Leadership"]', '["Corporate Finance", "Technology Strategy"]', 'Wharton School', '["Yahoo!", "Fortinet", "Siebel Systems"]'),
(4, 'Leo Ma', 'RoboForce', 'CEO', 'panelist', 'CEO of RoboForce, building advanced robotics and embodied AI systems', 'https://linkedin.com/in/leomarobotics', '["Robotics", "Computer Vision", "AI Research"]', '["Robotics", "Embodied AI"]', 'MIT (Robotics)', '["Boston Dynamics", "Tesla"]'),
(4, 'Stephen McGuire', 'UC Santa Cruz', 'Professor', 'panelist', 'Professor at UCSC Human Aware Robotics Exploration Lab', 'https://linkedin.com/in/stephenmcguire-ucsc', '["Academic Research", "Robotics"]', '["Human-Robot Interaction", "Robotics Research"]', 'Carnegie Mellon (PhD Robotics)', '["NASA", "MIT"]'),
(4, 'Tao Chen', 'Dexmate Robotics', 'CEO', 'panelist', 'CEO of Dexmate Robotics, developing dexterous manipulation systems', 'https://linkedin.com/in/taochendexmate', '["Robotics", "AI Research"]', '["Robotics", "Dexterous Manipulation"]', 'Stanford (PhD Mechanical Engineering)', '["Google X", "Willow Garage"]');

-- Event 5 & 13: Web3 × AI: Decentralized Intelligence Pitch
INSERT OR IGNORE INTO event_speakers (event_id, name, company, title, role, bio, linkedin_url, expertise, speaking_topics, education, previous_companies) VALUES
(5, 'Sergey Khusnetdinov', 'Ga^3in Ventures', 'Managing Partner', 'moderator', 'Managing Partner at Ga^3in Ventures and professor at SKEMA Business School', 'https://linkedin.com/in/sergeykhusnetdinov', '["Venture Capital", "Web3 Technology", "Academic Research"]', '["Web3 Investment", "AI Investment"]', 'SKEMA Business School (PhD)', '["McKinsey", "BCG"]'),
(13, 'Sergey Khusnetdinov', 'Ga^3in Ventures', 'Managing Partner', 'moderator', 'Managing Partner at Ga^3in Ventures and professor at SKEMA Business School', 'https://linkedin.com/in/sergeykhusnetdinov', '["Venture Capital", "Web3 Technology", "Academic Research"]', '["Web3 Investment", "AI Investment"]', 'SKEMA Business School (PhD)', '["McKinsey", "BCG"]');

-- Event 6: Enterprise AI Adoption Breakfast
INSERT OR IGNORE INTO event_speakers (event_id, name, company, title, role, bio, linkedin_url, expertise, speaking_topics, education, previous_companies) VALUES
(6, 'Justin Roberts', 'Revenue Pilot', 'Founder', 'speaker', 'Founder of Revenue Pilot, expert in sales leadership and revenue operations', 'https://linkedin.com/in/justinroberts-revenue', '["Sales Leadership", "Revenue Operations"]', '["Sales Leadership", "Revenue Growth"]', 'UC Berkeley', '["Salesforce", "HubSpot"]'),
(6, 'Jonathan Festejo', 'Salesbricks', 'Co-Founder & CEO', 'speaker', 'Co-Founder & CEO of Salesbricks, building sales automation tools', 'https://linkedin.com/in/jonathanfestejo', '["Sales Leadership", "Product Management"]', '["Sales Automation", "Revenue Growth"]', 'Stanford University', '["Microsoft", "Oracle"]');

-- Event 7 & 15: Cyber60: AI-Powered Security Innovation
INSERT OR IGNORE INTO event_speakers (event_id, name, company, title, role, bio, linkedin_url, expertise, speaking_topics, education, previous_companies) VALUES
(7, 'Fiona Lau', 'WorkDuo AI', 'Co-founder', 'speaker', 'Co-founder of WorkDuo AI, building AI-powered workplace tools', 'https://linkedin.com/in/fionalauworkduo', '["AI Development Tools", "Product Management", "Machine Learning"]', '["AI Workplace Tools", "Product Strategy"]', 'Stanford University', '["Google", "Airbnb"]'),
(7, 'Tony Wong', 'WorkDuo AI', 'Co-founder', 'speaker', 'Co-founder of WorkDuo AI, expert in AI and workplace automation', 'https://linkedin.com/in/tonywongworkduo', '["AI Development Tools", "Engineering Leadership", "Machine Learning"]', '["AI Automation", "Engineering Leadership"]', 'MIT', '["Facebook", "Uber"]'),
(15, 'Fiona Lau', 'WorkDuo AI', 'Co-founder', 'speaker', 'Co-founder of WorkDuo AI, building AI-powered workplace tools', 'https://linkedin.com/in/fionalauworkduo', '["AI Development Tools", "Product Management", "Machine Learning"]', '["AI Workplace Tools", "Product Strategy"]', 'Stanford University', '["Google", "Airbnb"]'),
(15, 'Tony Wong', 'WorkDuo AI', 'Co-founder', 'speaker', 'Co-founder of WorkDuo AI, expert in AI and workplace automation', 'https://linkedin.com/in/tonywongworkduo', '["AI Development Tools", "Engineering Leadership", "Machine Learning"]', '["AI Automation", "Engineering Leadership"]', 'MIT', '["Facebook", "Uber"]');

-- Event 8 & 16: Quantum AI: IBM Research Frontiers
INSERT OR IGNORE INTO event_speakers (event_id, name, company, title, role, bio, linkedin_url, twitter_url, expertise, speaking_topics, education, previous_companies) VALUES
(8, 'Malcolm Gladwell', 'Smart Talks with IBM', 'Author & Host', 'speaker', 'Bestselling author and host exploring technology and society intersections', 'https://linkedin.com/in/malcolmgladwell', 'https://twitter.com/gladwell', '["Technology Commentary", "Behavioral Psychology"]', '["Technology Impact on Society", "Innovation Patterns"]', 'University of Toronto', '["The New Yorker", "Washington Post"]'),
(8, 'Jay Gambetta', 'IBM Quantum', 'IBM Fellow & VP', 'speaker', 'Leading quantum computing research and quantum-classical hybrid algorithms at IBM', 'https://linkedin.com/in/jaygambetta', NULL, '["Quantum Computing", "AI Research"]', '["Quantum Computing", "Quantum-Classical Hybrid Systems"]', 'Griffith University (PhD Physics)', '["University of Queensland", "Yale University"]'),
(16, 'Malcolm Gladwell', 'Smart Talks with IBM', 'Author & Host', 'speaker', 'Bestselling author and host exploring technology and society intersections', 'https://linkedin.com/in/malcolmgladwell', 'https://twitter.com/gladwell', '["Technology Commentary", "Behavioral Psychology"]', '["Technology Impact on Society", "Innovation Patterns"]', 'University of Toronto', '["The New Yorker", "Washington Post"]'),
(16, 'Jay Gambetta', 'IBM Quantum', 'IBM Fellow & VP', 'speaker', 'Leading quantum computing research and quantum-classical hybrid algorithms at IBM', 'https://linkedin.com/in/jaygambetta', NULL, '["Quantum Computing", "AI Research"]', '["Quantum Computing", "Quantum-Classical Hybrid Systems"]', 'Griffith University (PhD Physics)', '["University of Queensland", "Yale University"]');

-- Event 11: BATTER UP! AI Startup Pitch Competition
INSERT OR IGNORE INTO event_speakers (event_id, name, company, title, role, bio, linkedin_url, expertise, speaking_topics, education, previous_companies) VALUES
(11, 'Marie-Ange Youm Tagne', 'Independent', 'Product Leader', 'speaker', 'Product leader with 20+ years at Meta, Intel, Amazon, Yahoo, Roku, expert in global product scaling', 'https://linkedin.com/in/marieangeyoumtagne', '["Product Management", "Technology Leadership", "Enterprise Software"]', '["Global Product Strategy", "Product Scaling"]', 'Stanford University (PhD)', '["Meta", "Amazon", "Intel", "Yahoo", "Roku"]'),
(11, 'Aivars Mirzo Lipenitis', 'Technology Consulting Group', 'Group CEO', 'moderator', 'Group CEO of technology and consulting companies, expert in startup-corporate partnerships', 'https://linkedin.com/in/aivarsmirzo', '["Corporate Development", "Technology Leadership"]', '["Corporate-Startup Partnerships", "Technology Strategy"]', 'Latvia University of Technology', '["McKinsey", "Deloitte"]');

-- Event 12: Physical AI Breakfast: Robotics & Embodied Intelligence
INSERT OR IGNORE INTO event_speakers (event_id, name, company, title, role, bio, linkedin_url, expertise, speaking_topics, education, previous_companies) VALUES
(12, 'Yi Zhang', 'UC Santa Cruz', 'Professor', 'moderator', 'Professor at UCSC specializing in AI research and machine learning', 'https://linkedin.com/in/yizhang-ucsc', '["Academic Research", "Machine Learning", "AI Research"]', '["AI Research", "Machine Learning"]', 'Stanford (PhD Computer Science)', '["Google Research", "Microsoft Research"]'),
(12, 'Ian Lane', 'UC Santa Cruz', 'Professor', 'panelist', 'Professor at UCSC specializing in agentic AI and autonomous systems', 'https://linkedin.com/in/ianlane-ucsc', '["AI Research", "Academic Research"]', '["Agentic AI", "Autonomous Systems"]', 'Carnegie Mellon (PhD)', '["CMU", "Google"]'),
(12, 'Antoine Raux', 'modelcode.ai', 'Co-founder', 'panelist', 'Co-founder of modelcode.ai, expert in AI model development and deployment', 'https://linkedin.com/in/antoineraux', '["AI Research", "Machine Learning", "Developer Tools"]', '["AI Model Development", "ML Engineering"]', 'Carnegie Mellon (PhD)', '["Google", "Uber"]'),
(12, 'David Wei', 'Turing.ai', 'VP', 'panelist', 'VP at Turing.ai, leading AI engineering and product development', 'https://linkedin.com/in/davidwei-turing', '["AI Engineering", "Product Management", "Machine Learning"]', '["AI Engineering", "Product Development"]', 'MIT', '["Facebook", "Netflix"]'),
(12, 'Jerry Li', 'LiveX.ai', 'CEO', 'panelist', 'CEO of LiveX.ai, building live AI interaction systems', 'https://linkedin.com/in/jerryli-livex', '["AI Research", "Product Management"]', '["Live AI Systems", "Real-time AI"]', 'Stanford', '["ByteDance", "TikTok"]');

-- Event 14: Enterprise AI Adoption Breakfast (continued)
INSERT OR IGNORE INTO event_speakers (event_id, name, company, title, role, bio, linkedin_url, expertise, speaking_topics, education, previous_companies) VALUES
(14, 'Ellen Damaso', 'Plus Ultra Capital Partners', 'Venture Partner', 'session_lead', 'Venture Partner and mindfulness expert leading wellness sessions for startup operators', 'https://linkedin.com/in/ellendamaso', '["Mindfulness", "Venture Capital"]', '["Mindfulness for Entrepreneurs", "Startup Wellness"]', 'UC Berkeley', '["Headspace", "Calm"]'),
(14, 'Jovena Natalis', 'Clutch Talent', 'Founder', 'presenter', 'Founder of Clutch Talent, expert in tech recruiting and career strategy', 'https://linkedin.com/in/jovenanatalis', '["Tech Recruiting", "Career Development"]', '["Tech Career Strategy", "Job Search Strategy"]', 'UC Berkeley', '["LinkedIn", "Google"]');